# Usa a imagem oficial do Nginx como base
FROM nginx:alpine

# Copia o arquivo HTML para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html/index.html

# Expõe a porta 80 para acesso externo
EXPOSE 80
